<?php
// Theme.php
// This file is used to define various color themes for the webpage.

// Select your desired theme here.
// You can change the theme name in the variable below to alter the webpage's appearance.
// Available themes: 'Ocean', 'Forest', 'Space', 'Desert', 'Volcano', 'Snowy Tundra', 'Magical Kingdom', 'Industrial City', 'Sunset Beach', 'Candy Land'
$selected_theme_name = 'Candy Land'; 

// Various color themes
$themes = [
    'Ocean' => [
        '--primary-color' => '#0077B6', 
        '--secondary-color' => '#00B4D8',
        '--text-color-light' => '#E0FBFC',
        '--text-color-medium' => '#ADE8F4',
        '--dark-base-color' => '#023E8A',
        '--gradient-start' => '#001D4A',
        '--gradient-end' => '#00509D',
        '--accent-green' => '#2EC4B6',
        '--accent-red' => '#EE5253',
        '--button-store-start' => '#FF6F61',
        '--button-store-end' => '#E63946',
        '--button-discord-start' => '#4895EF',
        '--button-discord-end' => '#0077B6',
        '--button-play-start' => '#5EEAD4',
        '--button-play-end' => '#2EC4B6',
        '--text-shadow-color-main' => 'rgba(0, 180, 216, 0.6), 0 0 25px rgba(173, 232, 244, 0.4)',
    ],
    'Forest' => [
        '--primary-color' => '#4CAF50',
        '--secondary-color' => '#8BC34A',
        '--text-color-light' => '#F1F8E9',
        '--text-color-medium' => '#DCEDC8',
        '--dark-base-color' => '#33691E',
        '--gradient-start' => '#1B5E20',
        '--gradient-end' => '#388E3C',
        '--accent-green' => '#AEEA00',
        '--accent-red' => '#D32F2F',
        '--button-store-start' => '#FF9800',
        '--button-store-end' => '#EF6C00',
        '--button-discord-start' => '#607D8B',
        '--button-discord-end' => '#455A64',
        '--button-play-start' => '#CDDC39',
        '--button-play-end' => '#AFB42B',
        '--text-shadow-color-main' => 'rgba(139, 195, 74, 0.6), 0 0 25px rgba(220, 237, 200, 0.4)',
    ],
    'Space' => [
        '--primary-color' => '#3F51B5',
        '--secondary-color' => '#2196F3',
        '--text-color-light' => '#E8EAF6',
        '--text-color-medium' => '#BBDEFB',
        '--dark-base-color' => '#1A237E',
        '--gradient-start' => '#000033',
        '--gradient-end' => '#1A237E',
        '--accent-green' => '#00E676',
        '--accent-red' => '#FF1744',
        '--button-store-start' => '#FF5252',
        '--button-store-end' => '#D50000',
        '--button-discord-start' => '#7C4DFF',
        '--button-discord-end' => '#651FFF',
        '--button-play-start' => '#00B8D4',
        '--button-play-end' => '#00838F',
        '--text-shadow-color-main' => 'rgba(33, 150, 243, 0.6), 0 0 25px rgba(187, 222, 251, 0.4)',
    ],
    'Desert' => [
        '--primary-color' => '#D69C2F',
        '--secondary-color' => '#FFC107',
        '--text-color-light' => '#FFFDE7',
        '--text-color-medium' => '#FFE082',
        '--dark-base-color' => '#8D6E63',
        '--gradient-start' => '#3E2723',
        '--gradient-end' => '#5D4037',
        '--accent-green' => '#8BC34A',
        '--accent-red' => '#FF5252',
        '--button-store-start' => '#FFB300',
        '--button-store-end' => '#FB8C00',
        '--button-discord-start' => '#81C784',
        '--button-discord-end' => '#4CAF50',
        '--button-play-start' => '#FFD54F',
        '--button-play-end' => '#FFCA28',
        '--text-shadow-color-main' => 'rgba(255, 193, 7, 0.6), 0 0 25px rgba(255, 224, 130, 0.4)',
    ],
    'Volcano' => [
        '--primary-color' => '#D84315',
        '--secondary-color' => '#FF7043',
        '--text-color-light' => '#FFF3E0',
        '--text-color-medium' => '#FFCCBC',
        '--dark-base-color' => '#212121',
        '--gradient-start' => '#000000',
        '--gradient-end' => '#424242',
        '--accent-green' => '#FFD600',
        '--accent-red' => '#E64A19',
        '--button-store-start' => '#FF8A65',
        '--button-store-end' => '#FF5722',
        '--button-discord-start' => '#795548',
        '--button-discord-end' => '#5D4037',
        '--button-play-start' => '#FFEB3B',
        '--button-play-end' => '#FBC02D',
        '--text-shadow-color-main' => 'rgba(255, 112, 67, 0.6), 0 0 25px rgba(255, 204, 188, 0.4)',
    ],
    'Snowy Tundra' => [
        '--primary-color' => '#64B5F6',
        '--secondary-color' => '#90CAF9',
        '--text-color-light' => '#F8F8FF',
        '--text-color-medium' => '#E3F2FD',
        '--dark-base-color' => '#263238',
        '--gradient-start' => '#1A293A',
        '--gradient-end' => '#37474F',
        '--accent-green' => '#AED581',
        '--accent-red' => '#E57373',
        '--button-store-start' => '#E0E0E0',
        '--button-store-end' => '#BDBDBD',
        '--button-discord-start' => '#81D4FA',
        '--button-discord-end' => '#4FC3F7',
        '--button-play-start' => '#C5CAE9',
        '--button-play-end' => '#9FA8DA',
        '--text-shadow-color-main' => 'rgba(144, 202, 249, 0.6), 0 0 25px rgba(227, 242, 253, 0.4)',
    ],
    'Magical Kingdom' => [
        '--primary-color' => '#7B1FA2',
        '--secondary-color' => '#BA68C8',
        '--text-color-light' => '#F3E5F5',
        '--text-color-medium' => '#E1BEE7',
        '--dark-base-color' => '#4A148C',
        '--gradient-start' => '#210042',
        '--gradient-end' => '#6A1B9A',
        '--accent-green' => '#FFC107',
        '--accent-red' => '#FF80AB',
        '--button-store-start' => '#FF80AB',
        '--button-store-end' => '#F48FB1',
        '--button-discord-start' => '#8C9EFF',
        '--button-discord-end' => '#536DFE',
        '--button-play-start' => '#FFEE58',
        '--button-play-end' => '#FFD600',
        '--text-shadow-color-main' => 'rgba(186, 104, 200, 0.6), 0 0 25px rgba(225, 190, 231, 0.4)',
    ],
    'Industrial City' => [
        '--primary-color' => '#757575',
        '--secondary-color' => '#9E9E9E',
        '--text-color-light' => '#EEEEEE',
        '--text-color-medium' => '#BDBDBD',
        '--dark-base-color' => '#212121',
        '--gradient-start' => '#0A0A0A',
        '--gradient-end' => '#424242',
        '--accent-green' => '#FFEB3B',
        '--accent-red' => '#F44336',
        '--button-store-start' => '#8D6E63',
        '--button-store-end' => '#6D4C41',
        '--button-discord-start' => '#4FC3F7',
        '--button-discord-end' => '#03A9F4',
        '--button-play-start' => '#FFEB3B',
        '--button-play-end' => '#FBC02D',
        '--text-shadow-color-main' => 'rgba(158, 158, 158, 0.6), 0 0 25px rgba(189, 189, 189, 0.4)',
    ],
    'Sunset Beach' => [
        '--primary-color' => '#FF8A65',
        '--secondary-color' => '#FFCC80',
        '--text-color-light' => '#FFFDE7',
        '--text-color-medium' => '#FFECB3',
        '--dark-base-color' => '#E65100',
        '--gradient-start' => '#BF360C',
        '--gradient-end' => '#FF6F00',
        '--accent-green' => '#8BC34A',
        '--accent-red' => '#D84315',
        '--button-store-start' => '#FFC107',
        '--button-store-end' => '#FFB300',
        '--button-discord-start' => '#81D4FA',
        '--button-discord-end' => '#4FC3F7',
        '--button-play-start' => '#FFEB3B',
        '--button-play-end' => '#FBC02D',
        '--text-shadow-color-main' => 'rgba(255, 204, 128, 0.6), 0 0 25px rgba(255, 236, 179, 0.4)',
    ],
    'Candy Land' => [
        '--primary-color' => '#EC407A',
        '--secondary-color' => '#AB47BC',
        '--text-color-light' => '#FCE4EC',
        '--text-color-medium' => '#F8BBD0',
        '--dark-base-color' => '#7B1FA2',
        '--gradient-start' => '#4A148C',
        '--gradient-end' => '#880E4F',
        '--accent-green' => '#CDDC39',
        '--accent-red' => '#EF5350',
        '--button-store-start' => '#FFAB40',
        '--button-store-end' => '#FF6E40',
        '--button-discord-start' => '#69F0FF',
        '--button-discord-end' => '#00E5FF',
        '--button-play-start' => '#FFEE58',
        '--button-play-end' => '#FFD600',
        '--text-shadow-color-main' => 'rgba(171, 71, 188, 0.6), 0 0 25px rgba(248, 187, 208, 0.4)',
    ],
];

// Check if the selected theme exists, otherwise, default to 'Ocean'.
$current_theme = $themes[$selected_theme_name] ?? $themes['Ocean'];

?>
